added support for Italian regions (one, all, all except one), added o…
michetonu/covid19-best-fit-evolution pull request #2
Opened 2020-03-25 18:32 UTC by eruffaldi

…ptional caching of web download, added optional stop repeat

2020-03-25 18:51 UTC, michetonu requested changes
Grazie! solo qualche commento

2020-03-25 18:51 UTC, michetonu commented on src/animate.py
> +def run(country, region= "", to_plot='confirmed', save=False, path=None,cached=False,repeat=True):
Mi faresti pep8 formatting per favore? (e.g. spazi tra gli argomenti delle funzioni) 

for readability :)

2020-03-25 18:51 UTC, michetonu commented on src/animate.py
> +        Region of the given contry, currently only for Italy supportorted ('all', NAME or mNAME for excluding NAME region)
`currently supported only for Italy`

2020-03-25 18:51 UTC, michetonu commented on src/animate.py
> +        url = config.ITALYREGION_URL
error/warning otherwise?

2020-03-25 18:51 UTC, michetonu commented on src/animate.py
> +                print("filtering")
toglierei i prints, o semmai li metterei usando logging (o almeno almeno wrapped in un `if verbose:`, con verbose come parametro della funzione)

2020-03-25 22:48 UTC, eruffaldi commented
All done

2020-03-26 10:36 UTC, michetonu approved these changes

2020-03-26 10:36 UTC, merged